nodeapp:
  build: .
  container_name: nodeapp
  command: node index.js
  tty: true
  ports:
    - '8888:8888'
  environment:
    - PORT=8888
  volumes:
    - ./server:/app
    - /app/node_modules
    - /app/db
    - www:/app/out
nginx:
  image: nginx
  container_name: nginx
  ports:
    - '8080:8080'
  volumes:
    - ./nginx:/etc/nginx/conf.d:ro
    - www:/www/app:ro
  links:
    - 'nodeapp'
